#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-v2

write_files:
  - path: /opt/app/secrets/cert.pem
    permissions: '0444'
    content: |
      ${indent(6, cert_pem)}

  - path: /opt/app/secrets/key.pem
    permissions: '0400'
    content: |
      ${indent(6, key_pem)}

  - path: /opt/app/docker-compose.yaml
    permissions: '0644'
    content: |
      ${indent(6, docker_compose)}

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - cd /opt/app && docker compose up -d